name: OpenAI Chatbot

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types: [created, edited]

jobs:
  run-openai:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/chatgpt-bot@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}